version: "3"

networks:
  store:
    driver: bridge

services:
  app:
    container_name: server-container
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - store
    env_file:
      - .env
  
  db:
    container_name: mysql-container
    image: mysql
    env_file:
      - .env
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_CHARSET: ${MYSQL_INITDB_CHARSET}
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
    - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - store
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u root", "-p ${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 12s
      retries: 10
      start_period: 0s

volumes:
  data: