name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql
        env:
          MYSQL_DATABASE: storedb
          MYSQL_USER: ruslan
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_INITDB_CHARSET: utf8mb4
          MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test

