name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Start MySQL service
        uses: docker-compose-action@v1
        with:
          compose-file: ./docker-compose.yml
          detach-keys: ctrl-b
          service: db
      - name: Wait for MySQL to start
        run: |
          while ! mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} --silent; do
            echo 'Waiting for MySQL to start...'
            sleep 5
          done
      - name: Unit tests
        run: npm run test
      - name: Unit tests
        run: npm run test
